# Generated by Django 5.2 on 2026-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_update_project_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
