# Generated by Django 6.0.1 on 2026-02-16 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
    ]
